# Variable Group 'Mule Config Variable' was defined in the Variables tab
variables:
- name: BuildParameters.mavenPOMFile
  value: pom.xml
trigger:
  branches:
    include:
    - refs/heads/dev
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/dev
stages:
- stage: build
  jobs:
    - job: Job_1
      displayName: Agent job 1
      pool:
        vmImage: ubuntu-latest
      steps:
      - checkout: self
        clean: true
        fetchTags: false
      - task: DownloadSecureFile@1
        name: securityFIle
        displayName: Download secure file
        inputs:
          secureFile: ff7ada31-94d0-4c12-aace-0430ac900f3f
      - task: Maven@3
        displayName: Maven pom.xml
        inputs:
          mavenPOMFile: $(BuildParameters.mavenPOMFile)
          goals: clean package
          options: -DskipMunitTests -DattachMuleSources
      - task: PublishPipelineArtifact@1
        displayName: Build Mulesoft artifacts
        inputs:
          artifactName: Mulesoft API artifacts
      - task: Maven@3
        displayName: Munits
        inputs:
          goals: 'clean test -s $(securityFIle.secureFilePath) '
          options: -Denv=$(env) -DskipMunits
      - task: Maven@3
        displayName: Maven pom.xml
        enabled: False
        inputs:
          goals: clean package deploy -DmuleDeploy

- stage: deploy
  jobs:
    - job: Job_2
      displayName: Agent job 2
      pool:
        vmImage: ubuntu-latest
        steps:
        - task: DownloadSecureFile@1
          displayName: 'Download secure file'
          inputs:
            secureFile: settings.xml
        
        - task: Maven@3
          displayName: 'Maven $(System.DefaultWorkingDirectory)/_Mulesoft Build Pipeline/Mulesoft API artifacts/s/pom.xml'
          inputs:
            mavenPomFile: '$(System.DefaultWorkingDirectory)/_Mulesoft Build Pipeline/Mulesoft API artifacts/s/pom.xml'
            goals: 'clean package deploy -DmuleDeploy'