
trigger:
- main

pool:
  vmImage: ubuntu-latest
stages: 
- stage: build
  jobs: 
  - job: buildpackage
    pool:
       vmImage: ubuntu-latest
    steps:
    - task: DownloadSecureFile@1
      displayName: 'Download secure file'
      inputs:
        secureFile: 'ff7ada31-94d0-4c12-aace-0430ac900f3f'

    - task: Maven@3
      displayName: 'Maven pom.xml'
      inputs:
        mavenPomFile: '$(Parameters.mavenPOMFile)'
        goals: 'clean package'
        options: '-DskipMunitTests -DattachMuleSources'

    - task: PublishPipelineArtifact@1
      displayName: 'Build Mulesoft artifacts'
      inputs:
        artifact: 'Mulesoft API artifacts'

    - task: Maven@3
      displayName: Munits
      inputs:
        goals: 'clean test -s $(securityFIle.secureFilePath) '
        options: '-Denv=$(env) -DskipMunits'
- stage: Deploy
jobs:
- job: startdeployment
  pool:
    vmImage: ubuntu-latest
  steps:
- task: DownloadSecureFile@1
  displayName: 'Download secure file'
  inputs:
    secureFile: settings.xml
    steps:
- task: Maven@3
  displayName: 'Maven $(System.DefaultWorkingDirectory)/_Mulesoft Build Pipeline/Mulesoft API artifacts/s/pom.xml'
  inputs:
    mavenPomFile: '$(System.DefaultWorkingDirectory)/_Mulesoft Build Pipeline/Mulesoft API artifacts/s/pom.xml'
    goals: 'clean package deploy -DmuleDeploy' 